FROM golang:1.21-alpine AS builder

# Move to working directory (/app).
WORKDIR /app

# Copy and download dependency using go mod.
COPY go.mod go.sum ./
RUN go mod download

# Copy the code into the container.
COPY . .

ENV HOST 0.0.0.0
ENV PORT 8000

# Set necessary environment variables needed for our image and build the API server.
ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64
RUN go build -ldflags="-s -w" -o /bin/swctl ./cmd

# Remove all source code files
RUN rm -r *

# RUN rm -rf ./internal && rm -rf ./cmd && rm -rf ./pkg && rm -rf ./test && rm -rf ./docs
# RUN cp ./bin/exe /bin/exe