FROM golang:1.22-alpine AS builder

# Move to working directory (/app).
WORKDIR /app

# Copy and download dependency using go mod.
COPY go.mod go.sum ./
RUN go mod download

# Copy the code into the container.
COPY . .

ENV HOST 0.0.0.0
ENV PORT 8000

# Set necessary environment variables needed for our image and build the API server.
ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64
# Copy migration files to /tmp
RUN cp -r pkg/migration /tmp
# Build the application
RUN go build -ldflags="-s -w" -o /bin/swipe ./cmd

# Remove all source code files
RUN rm -r *
# Copy migration files back to /app
RUN mkdir -p pkg && cp -r /tmp/migration/ pkg
# Clean up
RUN go clean -modcache