# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/vnpay.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'proto/vnpay.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/vnpay.proto\x12\x07payment\"\x93\x01\n\x0ePaymentRequest\x12\x12\n\norder_type\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x03\x12\x12\n\norder_desc\x18\x04 \x01(\t\x12\x11\n\tbank_code\x18\x05 \x01(\t\x12\x10\n\x08language\x18\x06 \x01(\t\x12\x12\n\nip_address\x18\x07 \x01(\t\"H\n\x0fPaymentResponse\x12\x13\n\x0bpayment_url\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\"\xcb\x02\n\x14PaymentReturnRequest\x12\x13\n\x0bvnp_TmnCode\x18\x01 \x01(\t\x12\x12\n\nvnp_Amount\x18\x02 \x01(\x04\x12\x14\n\x0cvnp_BankCode\x18\x03 \x01(\t\x12\x16\n\x0evnp_BankTranNo\x18\x04 \x01(\t\x12\x14\n\x0cvnp_CardType\x18\x05 \x01(\t\x12\x13\n\x0bvnp_PayDate\x18\x06 \x01(\t\x12\x15\n\rvnp_OrderInfo\x18\x07 \x01(\t\x12\x19\n\x11vnp_TransactionNo\x18\x08 \x01(\x04\x12\x18\n\x10vnp_ResponseCode\x18\t \x01(\t\x12\x1d\n\x15vnp_TransactionStatus\x18\n \x01(\t\x12\x12\n\nvnp_TxnRef\x18\x0b \x01(\t\x12\x1a\n\x12vnp_SecureHashType\x18\x0c \x01(\t\x12\x16\n\x0evnp_SecureHash\x18\r \x01(\t\"\xb4\x01\n\x15PaymentReturnResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x10\n\x08order_id\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x03\x12\x12\n\norder_desc\x18\x05 \x01(\t\x12\x19\n\x11vnp_TransactionNo\x18\x06 \x01(\t\x12\x18\n\x10vnp_ResponseCode\x18\x07 \x01(\t\x12\x0f\n\x07success\x18\x08 \x01(\x08\"\x0f\n\rStatusRequest\"2\n\x0eStatusResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\xe3\x01\n\x05VNPay\x12>\n\x0b\x43heckStatus\x12\x16.payment.StatusRequest\x1a\x17.payment.StatusResponse\x12\x43\n\x0eProcessPayment\x12\x17.payment.PaymentRequest\x1a\x18.payment.PaymentResponse\x12U\n\x14ProcessPaymentReturn\x12\x1d.payment.PaymentReturnRequest\x1a\x1e.payment.PaymentReturnResponseB\nZ\x08/paymentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.vnpay_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\010/payment'
  _globals['_PAYMENTREQUEST']._serialized_start=31
  _globals['_PAYMENTREQUEST']._serialized_end=178
  _globals['_PAYMENTRESPONSE']._serialized_start=180
  _globals['_PAYMENTRESPONSE']._serialized_end=252
  _globals['_PAYMENTRETURNREQUEST']._serialized_start=255
  _globals['_PAYMENTRETURNREQUEST']._serialized_end=586
  _globals['_PAYMENTRETURNRESPONSE']._serialized_start=589
  _globals['_PAYMENTRETURNRESPONSE']._serialized_end=769
  _globals['_STATUSREQUEST']._serialized_start=771
  _globals['_STATUSREQUEST']._serialized_end=786
  _globals['_STATUSRESPONSE']._serialized_start=788
  _globals['_STATUSRESPONSE']._serialized_end=838
  _globals['_VNPAY']._serialized_start=841
  _globals['_VNPAY']._serialized_end=1068
# @@protoc_insertion_point(module_scope)
