# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import vnpay_pb2 as proto_dot_vnpay__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/vnpay_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VNPayStub(object):
    """Định nghĩa dịch vụ PaymentService
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckStatus = channel.unary_unary(
                '/payment.VNPay/CheckStatus',
                request_serializer=proto_dot_vnpay__pb2.StatusRequest.SerializeToString,
                response_deserializer=proto_dot_vnpay__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ProcessPayment = channel.unary_unary(
                '/payment.VNPay/ProcessPayment',
                request_serializer=proto_dot_vnpay__pb2.PaymentRequest.SerializeToString,
                response_deserializer=proto_dot_vnpay__pb2.PaymentResponse.FromString,
                _registered_method=True)
        self.ProcessPaymentReturn = channel.unary_unary(
                '/payment.VNPay/ProcessPaymentReturn',
                request_serializer=proto_dot_vnpay__pb2.PaymentReturnRequest.SerializeToString,
                response_deserializer=proto_dot_vnpay__pb2.PaymentReturnResponse.FromString,
                _registered_method=True)


class VNPayServicer(object):
    """Định nghĩa dịch vụ PaymentService
    """

    def CheckStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessPayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessPaymentReturn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VNPayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckStatus,
                    request_deserializer=proto_dot_vnpay__pb2.StatusRequest.FromString,
                    response_serializer=proto_dot_vnpay__pb2.StatusResponse.SerializeToString,
            ),
            'ProcessPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessPayment,
                    request_deserializer=proto_dot_vnpay__pb2.PaymentRequest.FromString,
                    response_serializer=proto_dot_vnpay__pb2.PaymentResponse.SerializeToString,
            ),
            'ProcessPaymentReturn': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessPaymentReturn,
                    request_deserializer=proto_dot_vnpay__pb2.PaymentReturnRequest.FromString,
                    response_serializer=proto_dot_vnpay__pb2.PaymentReturnResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'payment.VNPay', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('payment.VNPay', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VNPay(object):
    """Định nghĩa dịch vụ PaymentService
    """

    @staticmethod
    def CheckStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.VNPay/CheckStatus',
            proto_dot_vnpay__pb2.StatusRequest.SerializeToString,
            proto_dot_vnpay__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.VNPay/ProcessPayment',
            proto_dot_vnpay__pb2.PaymentRequest.SerializeToString,
            proto_dot_vnpay__pb2.PaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessPaymentReturn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.VNPay/ProcessPaymentReturn',
            proto_dot_vnpay__pb2.PaymentReturnRequest.SerializeToString,
            proto_dot_vnpay__pb2.PaymentReturnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
