// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth": {
            "get": {
                "description": "check email address before login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account_management"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "email address",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.OK"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Login account.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account_management"
                ],
                "parameters": [
                    {
                        "description": "Login",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.LoginSchema"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.LoginMessage"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "get": {
                "description": "logout user from the service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account_management"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.OK"
                        }
                    }
                }
            }
        },
        "/auth/signup": {
            "post": {
                "description": "Register account for admin.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account_management"
                ],
                "parameters": [
                    {
                        "description": "Sign Up",
                        "name": "sign_up",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.SignUpSchema"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.SignUpMessage"
                        }
                    }
                }
            }
        },
        "/categories": {
            "get": {
                "description": "get categories",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "parameters": [
                    {
                        "type": "number",
                        "description": "limit number",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Slices-domain_Categories"
                        }
                    }
                }
            },
            "post": {
                "description": "insert new category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "parameters": [
                    {
                        "description": "Categories Request",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CategoriesSwagger"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.OK"
                        }
                    }
                }
            }
        },
        "/collections": {
            "get": {
                "description": "create collections",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "position of collections",
                        "name": "position",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "limit of cards banner slices",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.CollectionSliceSchema"
                        }
                    }
                }
            },
            "post": {
                "description": "create collections",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "parameters": [
                    {
                        "description": "collections Request",
                        "name": "collection",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CollectionSchemaSwagger"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.CollectionUploadSchema"
                        }
                    }
                }
            }
        },
        "/collections/headline": {
            "get": {
                "description": "get list of headline banner",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "position of collections",
                        "name": "position",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "limit headline of collections",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.HeadlineBannerSlices"
                        }
                    }
                }
            },
            "post": {
                "description": "create headline banner into collections",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "parameters": [
                    {
                        "description": "headline banner data request",
                        "name": "banner",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.HeadlineBannerSchema"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.OK"
                        }
                    }
                }
            }
        },
        "/collections/img": {
            "put": {
                "description": "create collections",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "parameters": [
                    {
                        "type": "file",
                        "description": "image of collections",
                        "name": "img",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "collections identifier",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.OK"
                        }
                    }
                }
            }
        },
        "/common/healthcheck": {
            "get": {
                "description": "health check api server.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "common"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/common/worker": {
            "get": {
                "description": "health check worker consume server.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "common"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/inventories": {
            "get": {
                "description": "get all product from inventory",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "parameters": [
                    {
                        "type": "number",
                        "description": "page",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "limit",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.InventoryStockSchema"
                        }
                    }
                }
            },
            "post": {
                "description": "add product to inventories",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "parameters": [
                    {
                        "description": "Inventories Request",
                        "name": "InventoryStruct",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.InventoryStruct"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.OK"
                        }
                    }
                }
            }
        },
        "/inventories/details": {
            "get": {
                "description": "get product availability in inventories",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "parameters": [
                    {
                        "type": "number",
                        "description": "product id",
                        "name": "pid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "ram",
                        "name": "ram",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "ssd",
                        "name": "ssd",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "color",
                        "name": "color",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.InventorySchema"
                        }
                    }
                }
            }
        },
        "/oauth2/login": {
            "get": {
                "description": "Auth0 Login form.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "common"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/products": {
            "get": {
                "description": "get product information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "limit number of products",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Slices-domain_ProductSchema"
                        }
                    }
                }
            },
            "put": {
                "description": "update product information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "parameters": [
                    {
                        "description": "Product Information Request",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UpdateProductInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.OK"
                        }
                    }
                }
            },
            "post": {
                "description": "create new product",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "parameters": [
                    {
                        "description": "Product Request",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Product"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.CreateProductSchema"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete product by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "product id",
                        "name": "pid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.OK"
                        }
                    }
                }
            }
        },
        "/products/img": {
            "post": {
                "description": "insert new product image",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of product",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "image of product",
                        "name": "img",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.OK"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/domain.Error"
                        }
                    }
                }
            }
        },
        "/purchase/carts": {
            "get": {
                "description": "get list of items from carts",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "purchase"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "uid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.CartSlices"
                        }
                    }
                }
            },
            "post": {
                "description": "add item to carts.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "purchase"
                ],
                "parameters": [
                    {
                        "description": "cart insert request",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CartInsert"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.OK"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete item from carts",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "purchase"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "user id",
                        "name": "uid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "inventories id",
                        "name": "wid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.OK"
                        }
                    }
                }
            }
        },
        "/purchase/orders": {
            "get": {
                "description": "get list of orders.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "purchase"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "uid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.OrderSchema"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "create order.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "purchase"
                ],
                "parameters": [
                    {
                        "description": "order insert request",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateOrderSchema"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.OK"
                        }
                    }
                }
            }
        },
        "/suppliers": {
            "get": {
                "description": "get suppliers information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "limit number of suppliers",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Slices-domain_Suppliers"
                        }
                    }
                }
            },
            "post": {
                "description": "insert new suppliers information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "parameters": [
                    {
                        "description": "Suppliers Request",
                        "name": "SupplierSchema",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.SupplierSchema"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.OK"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "get information for users.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account_management"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.UserSchema"
                        }
                    }
                }
            },
            "put": {
                "description": "update information for users.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account_management"
                ],
                "parameters": [
                    {
                        "description": "Update Users",
                        "name": "UserSchema",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UserUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.OK"
                        }
                    }
                }
            }
        },
        "/users/image": {
            "put": {
                "description": "update information for users.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account_management"
                ],
                "parameters": [
                    {
                        "type": "file",
                        "description": "image of collections",
                        "name": "img",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.OK"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.CartInsert": {
            "type": "object",
            "required": [
                "inventory_id",
                "quantity",
                "user_id"
            ],
            "properties": {
                "inventory_id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "domain.CartSchema": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "img": {
                    "type": "string"
                },
                "product_name": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "domain.CartSlices": {
            "type": "object",
            "properties": {
                "products": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.CartSchema"
                    }
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "domain.Categories": {
            "type": "object",
            "required": [
                "description",
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.CategoriesSwagger": {
            "type": "object",
            "required": [
                "description",
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.CollectionBodySwagger": {
            "type": "object",
            "required": [
                "description",
                "subtitle",
                "text_color",
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "subtitle": {
                    "type": "string"
                },
                "text_color": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "domain.CollectionSchemaSwagger": {
            "type": "object",
            "required": [
                "body",
                "headline",
                "position"
            ],
            "properties": {
                "body": {
                    "$ref": "#/definitions/domain.CollectionBodySwagger"
                },
                "headline": {
                    "type": "string"
                },
                "position": {
                    "type": "string"
                }
            }
        },
        "domain.CollectionSliceBody": {
            "type": "object",
            "required": [
                "description",
                "subtitle",
                "text_color",
                "title"
            ],
            "properties": {
                "created": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "subtitle": {
                    "type": "string"
                },
                "text_color": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "domain.CollectionSliceSchema": {
            "type": "object",
            "properties": {
                "card_banner": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.CollectionSliceBody"
                    }
                },
                "headline": {
                    "type": "string"
                },
                "position": {
                    "type": "string"
                }
            }
        },
        "domain.CollectionUploadSchema": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "domain.CreateOrderSchema": {
            "type": "object",
            "properties": {
                "product": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "inventory_id": {
                                "type": "integer"
                            },
                            "quantity": {
                                "type": "integer"
                            }
                        }
                    }
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "domain.CreateProductSchema": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "domain.Error": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                }
            }
        },
        "domain.HeadlineBannerBody": {
            "type": "object",
            "required": [
                "headline"
            ],
            "properties": {
                "headline": {
                    "type": "string"
                }
            }
        },
        "domain.HeadlineBannerSchema": {
            "type": "object",
            "required": [
                "body",
                "position"
            ],
            "properties": {
                "body": {
                    "$ref": "#/definitions/domain.HeadlineBannerBody"
                },
                "created": {
                    "type": "string"
                },
                "position": {
                    "type": "string"
                }
            }
        },
        "domain.HeadlineBannerSlices": {
            "type": "object",
            "properties": {
                "headlines": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.HeadlineBannerSlicesBody"
                    }
                },
                "position": {
                    "type": "string"
                }
            }
        },
        "domain.HeadlineBannerSlicesBody": {
            "type": "object",
            "required": [
                "headline"
            ],
            "properties": {
                "created": {
                    "type": "string"
                },
                "headline": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "domain.InventorySchema": {
            "type": "object",
            "required": [
                "available",
                "currency_code",
                "model",
                "price",
                "product_id"
            ],
            "properties": {
                "available": {
                    "type": "string"
                },
                "currency_code": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "price": {
                    "type": "string"
                },
                "product_id": {
                    "type": "string"
                },
                "specs": {
                    "$ref": "#/definitions/domain.InventorySpecsDetail"
                }
            }
        },
        "domain.InventorySpecsDetail": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "color_image": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "ram": {
                    "type": "string"
                },
                "ssd": {
                    "type": "string"
                }
            }
        },
        "domain.InventoryStockSchema": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "integer"
                },
                "all": {
                    "type": "integer"
                },
                "archive": {
                    "type": "integer"
                },
                "draft": {
                    "type": "integer"
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "stock": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.InventorySchema"
                    }
                }
            }
        },
        "domain.InventoryStruct": {
            "type": "object",
            "required": [
                "available",
                "currency_code",
                "model",
                "price",
                "product_id"
            ],
            "properties": {
                "available": {
                    "type": "string"
                },
                "currency_code": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "price": {
                    "type": "string"
                },
                "product_id": {
                    "type": "string"
                },
                "specs": {
                    "$ref": "#/definitions/domain.InventorySpecsDetail"
                }
            }
        },
        "domain.LoginMessage": {
            "type": "object",
            "required": [
                "email",
                "success",
                "token"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "domain.LoginSchema": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "domain.OK": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                }
            }
        },
        "domain.OrderSchema": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "products": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ProductOrderSchema"
                    }
                },
                "status": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "user_email": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "user_name": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "domain.Product": {
            "type": "object",
            "required": [
                "category_id",
                "description",
                "name",
                "price",
                "status",
                "supplier_id"
            ],
            "properties": {
                "RAM": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "SSD": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "category_id": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "display": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "string"
                },
                "screen": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "supplier_id": {
                    "type": "string"
                }
            }
        },
        "domain.ProductOrderSchema": {
            "type": "object",
            "properties": {
                "currency_code": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "inventory_id": {
                    "type": "integer"
                },
                "order_id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                },
                "total_amount": {
                    "type": "string"
                }
            }
        },
        "domain.ProductSchema": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "string"
                },
                "spec": {
                    "$ref": "#/definitions/domain.Specs"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "domain.SignUpMessage": {
            "type": "object",
            "required": [
                "msg",
                "success"
            ],
            "properties": {
                "msg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "domain.SignUpSchema": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "last_name",
                "password",
                "phone_number"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                }
            }
        },
        "domain.Slices-domain_Categories": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Categories"
                    }
                }
            }
        },
        "domain.Slices-domain_ProductSchema": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ProductSchema"
                    }
                }
            }
        },
        "domain.Slices-domain_Suppliers": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Suppliers"
                    }
                }
            }
        },
        "domain.Specs": {
            "type": "object",
            "properties": {
                "RAM": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "SSD": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "display": {
                    "type": "string"
                },
                "screen": {
                    "type": "string"
                }
            }
        },
        "domain.SupplierSchema": {
            "type": "object",
            "required": [
                "email",
                "name"
            ],
            "properties": {
                "city": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "street": {
                    "type": "string"
                },
                "ward": {
                    "type": "string"
                }
            }
        },
        "domain.Suppliers": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.UpdateProductInfo": {
            "type": "object",
            "required": [
                "category_id",
                "description",
                "id",
                "name",
                "price",
                "status",
                "supplier_id"
            ],
            "properties": {
                "RAM": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "SSD": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "category_id": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "display": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "string"
                },
                "screen": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "supplier_id": {
                    "type": "string"
                }
            }
        },
        "domain.UserSchema": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "id",
                "image",
                "last_name",
                "phone_number",
                "role",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "domain.UserUpdate": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "id",
                "last_name",
                "phone_number",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Swipe API documentation",
	Description:      "This is a documentation for the Swipe API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
